import type { NextPage } from "next";
import Head from "next/head";
import Board from "../components/Board";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const puzzle = trpc.sudoku.makepuzzle.useQuery();

  return (
    <>
      <Head>
        <title>Sudoku</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto max-w-lg flex flex-col">
        <Board />
      </main>
    </>
  );
};

export default Home;
