import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const puzzle = trpc.sudoku.makepuzzle.useQuery();
  
  return (
    <>
      <Head>
        <title>Sudoku</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <p>{hello.data?.greeting}</p>
      </main>
    </>
  );
};

export default Home;
